apiVersion: v1
kind: PersistentVolume
metadata:
  name: challenge-pv

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/challenge-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: challenge-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod 
  labels:
    name: mypod 

spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

    volumeMounts:
      - mountPath: /var/www/html
        name: challenge-vl   
          
  volumes:
    - name: challenge-vl
      persistentVolumeClaim:
        claimName: challenge-pvc